version: 2.1

orbs:
  common: vidsy/common@volatile
  docker: vidsy/docker@volatile
  go: vidsy/go@volatile

ignore-master: &ignore-master
  filters:
    branches:
      ignore: master

workflows:
  commit:
    jobs:
      - common/check-version:
          <<: *ignore-master
      - docker/build:
          <<: *ignore-master
      - go/deploy:
          context: org-docker-hub
          deploy-to-ecr: false
          filters:
            branches:
              only:
                - master
            tags:
              only:
                - /[0-9]+\.[0-9]+\.[0-9]+/
